---
mappings:
  - path: /ping
    contentType: text/plain
    template: pong
  - path: /test/123
    headers:
      X-test: val2
    query:
      action: test
    contentType: application/json
    template: |-
      {
        "widget": {
          "debug": "on",
          "window": {
              "title": "Sample Konfabulator Widget",
              "name": "main_window",
              "width": 500,
              "height": 500
          }
        }
      }
  - path: /test/another
    headers:
      X-test: val
    query:
      latency: true
    contentType: application/json
    template: |-
      {
        "widget": {
          "debug": "on",
          "window": {
              "title": "Sample Konfabulator Widget",
              "name": "main_window",
              "width": 500,
              "height": 500,
              "latency": true
          }
        }
      }